language: python

sudo: false

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
  # Directory where tests are run from
  - TEST_DIR=/tmp/test_dir/
  - MODULE=openml
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" SKLEARN_VERSION="0.21.2"
  - DISTRIB="conda" PYTHON_VERSION="3.6" SKLEARN_VERSION="0.21.2"
  - DISTRIB="conda" PYTHON_VERSION="3.7" SKLEARN_VERSION="0.21.2" RUN_FLAKE8="true" SKIP_TESTS="true"
  - DISTRIB="conda" PYTHON_VERSION="3.7" SKLEARN_VERSION="0.21.2" COVERAGE="true" DOCPUSH="true"
  - DISTRIB="conda" PYTHON_VERSION="3.7" SKLEARN_VERSION="0.20.2"
  # Checks for older scikit-learn versions (which also don't nicely work with
  # Python3.7)
  - DISTRIB="conda" PYTHON_VERSION="3.6" SKLEARN_VERSION="0.19.2"
  - DISTRIB="conda" PYTHON_VERSION="3.6" SKLEARN_VERSION="0.18.2" SCIPY_VERSION=1.2.0

# Travis issue
# https://github.com/travis-ci/travis-ci/issues/8920
before_install:
 - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh && source ci_scripts/create_doc.sh $TRAVIS_BRANCH "doc_result"

# travis will check the deploy on condition, before actually running before_deploy
# before_deploy: source ci_scripts/create_doc.sh $TRAVIS_BRANCH "doc_result"

# For more info regarding the deploy process and the github token look at:
# https://docs.travis-ci.com/user/deployment/pages/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    all_branches: true
    condition: $doc_result = "success"
  local_dir: doc/$TRAVIS_BRANCH
