language: python

sudo: false

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
  # Directory where tests are run from
  - TEST_DIR=/tmp/test_dir/
  - MODULE=openml
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="2.7" SKLEARN_VERSION="0.18.2"
  - DISTRIB="conda" PYTHON_VERSION="3.5" SKLEARN_VERSION="0.18.2"
  - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true" SKLEARN_VERSION="0.18.2"
  - DISTRIB="conda" PYTHON_VERSION="3.6" EXAMPLES="true" SKLEARN_VERSION="0.18.2"
  - DISTRIB="conda" PYTHON_VERSION="3.6" DOCTEST="true" SKLEARN_VERSION="0.18.2"
#  - DISTRIB="conda" PYTHON_VERSION="3.7" SKLEARN_VERSION="0.18.2"

install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BOT
  keep-history: true
  on:
    all_branches: true
    condition: $(bash ci_scripts/create_doc.sh $TRAVIS_BRANCH) = success
  local_dir: doc/$TRAVIS_BRANCH
