name: dist-check

on: [push, pull_request]

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: build dist
      run: |
        python setup.py sdist
    - name: twine check
      run: |
        pip install twine
        last_dist=$(ls -t dist/openml-*.tar.gz | head -n 1)
        twine check $last_dist
    - name: install dist
      run: |
        last_dist=$(ls -t dist/openml-*.tar.gz | head -n 1)
        pip install $last_dist
    - name: PEP 561 Compliance
      run: |
        pip install mypy
        cd ..  # required to use the installed version of openml
        if ! python -m mypy -c "import openml"; then exit 1; fi
