name: Docs
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          pip install -e .[docs,examples]
    - name: Make docs
      run: |
        cd doc
        make html
    - name: Check links
      run: |
        cd doc
        make linkcheck
    - name: Pull latest gh-pages
      if: (contains(github.ref, 'develop') || contains(github.ref, 'main')) && github.event_name == 'push'
      run: |
        cd ..
        git clone https://github.com/openml/openml-python.git --branch gh-pages --single-branch gh-pages
    - name: Copy new doc into gh-pages
      if: (contains(github.ref, 'develop') || contains(github.ref, 'main')) && github.event_name == 'push'
      run: |
        branch_name=${GITHUB_REF##*/}
        cd ../gh-pages
        rm -rf $branch_name
        cp -r ../openml-python/doc/build/html $branch_name
    - name: Push to gh-pages
      if: (contains(github.ref, 'develop') || contains(github.ref, 'main')) && github.event_name == 'push'
      run: |
        last_commit=$(git log --pretty=format:"%an: %s")
        cd ../gh-pages
        branch_name=${GITHUB_REF##*/}
        git add $branch_name/
        git config --global user.name 'Github Actions'
        git config --global user.email 'not@mail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        # Only commit and push if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "$last_commit"
          git push
        else
          echo "Branch is up to date with origin/gh-pages, no need to update docs. Skipping."
        fi
