name: CI

on: [push, pull_request]

jobs:
  unittest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        scikit-learn: [0.21.2, 0.22.2, 0.23.1]
        exclude:
          - python-version: 3.8
            scikit-learn: 0.21.2
        include:
          - python-version: 3.6
            scikit-learn: 0.18.2            
          - python-version: 3.6
            scikit-learn: 0.19.2           
          - python-version: 3.6
            scikit-learn: 0.20.2
    
    steps:
    - uses: actions/checkout@v2
    - name: CI Python ${{ matrix.python-version }} scikit-learn ${{ matrix.scikit-learn }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (.[test])
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Install scikit-learn ${{ matrix.scikit-learn }}
      run: pip install scikit-learn==${{ matrix.scikit-learn }}
    - name: Pytest
      run: |
        pytest -n 4 --durations=20 --timeout=600 --timeout-method=thread -sv $PYTEST_ARGS $test_dir
